name: Scrape Hugging Face models

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '4,33 * * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scrape
      run: |        
        curl --request GET \
          --url 'https://huggingface.co/api/models?author=TheBloke' \
          | jq > TheBloke.json
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
